### PR TITLE
fix: rename Appliaction to Application

### PR DESCRIPTION
**Pull request by asantos00**
Hi there!Thanks for the amazing job on this. I've been using it and it works great, for such a short time! I also have a few ideas and plan to contribute back.

While browsing through the code I found out that the class exported by server had an apparent typo, it was `Appliaction` instead of `Application`.

This PR fixes it. Since it's an exported file in `server`, I don't know if anyone's using it by directly importing the file, but since it isn't exported in `mod.ts`, it should be fine.

**Note**: Another thing I noticed is that this repo isn't formatted according to `deno fmt`, should it?

### CODE REVIEW

**Comment by ije** [comment]
look great, thanks @asantos00

**Comment by ije** [comment]
i am using the vscode default formatter, i think it's good. `deno fmt` gives vary strong output i don't like... for example, i don't want the lines are ending with semicolon.

**Comment by Hunam6** [comment]
4 spaces tabs can be confusing when working on complex or long files, why don't use 2 spaces tabs @ije/@shadowtime2000?

**Comment by ije** [comment]
@Hunam6 make sense, i also perfer 2 spaces

**Pull request merged**
