### PR TITLE
compiler: properly handle import map subdirs

### LINKED ISSUE #247: Root directory import_map entries does not work for subdirs
The following `import_map.json`:
```json
{
    "imports": {
        "~/": "./",
        "lib": "./lib/mod.ts",
        "components": "./components/mod.ts",
        "graphql": "./lib/graphql.ts"
}
```
Results in the following errors:
```
INFO Compiling...
INFO Download https://esm.sh/@material-ui/core
ERROR Fetch module '/components/lib/mod.ts': No such file
INFO Download https://esm.sh/@apollo/client
INFO Download https://cdn.esm.sh/v33/_node_process.js
ERROR Fetch module '/components/lib/mod.ts': No such file
ERROR Fetch module '/components/lib/mod.ts': No such file
ERROR Fetch module '/components/lib/graphql.ts': No such file
ERROR Fetch module '/components/lib/mod.ts': No such file
ERROR Fetch module '/components/components/mod.ts': No such file
ERROR Fetch module '/components/lib/mod.ts': No such file
INFO Download https://esm.sh/url
INFO Download https://esm.sh/@material-ui/icons
ERROR Fetch module '/components/components/mod.ts': No such file
ERROR Fetch module '/components/lib/mod.ts': No such file
ERROR Fetch module '/components/lib/mod.ts': No such file
ERROR Fetch module '/components/lib/graphql.ts': No such file
ERROR Fetch module '/components/components/mod.ts': No such file
ERROR Fetch module '/components/lib/mod.ts': No such file
ERROR Fetch module '/components/lib/mod.ts': No such file
ERROR Fetch module '/components/components/mod.ts': No such file
ERROR Fetch module '/components/lib/graphql.ts': No such file
```

Using `/` instead of `./` works, but then VS Code cannot find the sources.

### PR DESCRIPTION
**Pull request by noverby**
Fixes #247

### CODE REVIEW

**Comment by hazae41** [comment]
The "comp" -> "components" mapping is not what I would expect, it doesn't respect the principle pf least astonishment

It would be better to use
"comps" -> "comps"
"components" -> "components"

Also, "components" is not an known directory for Aleph, it would be better to use "public"

**Comment by shadowtime2000** [comment]
I agree with @hazae41 on this. It doesn't make sense to have like an official `components` directory for Aleph either.

**Comment by noverby** [comment]
@hazae41 @shadowtime2000 The use of the components directory is just for testing the import_map functions. It does not mean that the directory is part of the official aleph.js folder hierarchy.

**Comment by ije** [comment]
@noverby ha, thanks 👍 in fact i already fixed this in my local branch

**Comment by ije** [comment]
but even in the testing, `comps` is better than `comp`

**Comment by ije** [comment]
but it is ok for me, if you don't want to rename the testing

**Comment by noverby** [comment]
@ije just give me 1 sec and I rename it

**Comment by noverby** [comment]
@ije done

**Comment by noverby** [comment]
@ije should I also include a dist build of the compiler to the PR?

**Comment by shadowtime2000** [comment]
@noverby Yes, you should probably do a rebuild of the WASM compiler and have it committed.

**Comment by ije** [comment]
@noverby can you please resolve the conflicts before i merge? thanks~

**Comment by noverby** [comment]
@ije The PR does not contain a rebuild of the compiler now. Can push a rebuild?

**Comment by ije** [comment]
@noverby no worries, the `publish` script will handle it: https://github.com/alephjs/aleph.js/blob/master/version.ts#L9

**Pull request merged**
