### PR TITLE
refactor: move code to import_map

### PR DESCRIPTION
**Pull request by mikelxk**
refactor: move code to import_map
update std to 0.92

### CODE REVIEW

**Comment by shadowtime2000** [comment]
Maybe I am getting the wrong idea here, but you are basically having runtime code use an import map? That doesn't really work because you have to manually specify import maps and stuff when running `aleph` then. So, I am going to close this. lmk if I am missing something here.

**Comment by ije** [comment]
@mikelxk thanks, unfortunately @shadowtime2000 is right, of course we can use the import_map but only in dev mode, in fact i already tried this but reverted before: https://github.com/alephjs/aleph.js/tree/8b0c830985053f4eab2ff0fb972f090f20b97a6b
however, deno supports remote import map and has a bug with install command: https://github.com/denoland/deno/issues/9877

**Comment by ije** [comment]
or we can handle the import map in the [install.ts](https://github.com/alephjs/aleph.js/blob/master/install.ts), i mean when people run the install.ts to install `aleph` command, it will also download the import map to local then pass it to the command.
@mikelxk do you have interest in implementing this?

**Comment by ije** [comment]
i'm going the reopen this to track this feature

**Comment by shadowtime2000** [comment]
@ije I have a couple comments about such feature but I think it would be better to close this and use an issue for tracking.

**Comment by ije** [comment]
@shadowtime2000 ok!

**Pull request closed without merging**
