### PR TITLE
fix: Error using tls in development mode

### LINKED ISSUE #508: Error using tls in development mode
```
TypeError: error sending request for url (http://localhost:3000/routes/index.tsx?ssr&v=l84gip33): connection closed before message completed
    at async importRouteModule (https://deno.land/x/aleph@1.0.0-beta.6/server/routing.ts:26:10)
    at async fetchRouteData (https://deno.land/x/aleph@1.0.0-beta.6/server/routing.ts:65:19)
    at async Server.handler (https://deno.land/x/aleph@1.0.0-beta.6/server/mod.ts:335:22)
    at async Server.#respond (https://deno.land/std@0.155.0/http/server.ts:298:18)
```

`server.ts`:

```ts
import { serve } from "aleph/react-server";
import routes from "./routes/_export.ts";
import unocss from "./unocss.config.ts";

serve({
  baseUrl: import.meta.url,
  router: { routes },
  ssr: true,
  unocss,

  hostname: "localhost.direct",
  certFile: "./scripts/localhost.direct/localhost.direct.crt",
  keyFile: "./scripts/localhost.direct/localhost.direct.key",
});

```

log:

```
Warning deno task is unstable and may drastically change in the future
Task dev deno run -A -q dev.ts
Initialized aleph-compiler WebAssembly in 98.71ms.
INFO [dev] Watching for file changes...
INFO Server ready on https://localhost:3000
Download http://localhost:3000/routes/index.tsx?ssr&v=l84gip33
```

cause by [server/routing.ts#L21](https://github.com/alephjs/aleph.js/blob/1.0.0-beta.6/server/routing.ts#L21):

```ts
  if (devPort) {
    url = `http://localhost:${devPort}${filename.slice(1)}?ssr&v=${(version ?? depGraph.globalVersion).toString(36)}`;
  } else {
    const root = appDir ?? (config?.baseUrl ? fromFileUrl(new URL(".", config.baseUrl)) : Deno.cwd());
    url = `file://${join(root, filename)}${version ? "#" + version.toString(36) : ""}`;
  }
  return await import(url);
```

### PR DESCRIPTION
**Pull request by ddosakura**
fix #508

### CODE REVIEW

**Review by ije — APPROVED** [review]
LGTM!

**Comment by ije** [comment]
can you please format the code? thanks!

**Comment by ddosakura** [comment]
> can you please format the code? thanks!

done

**Comment by ije** [comment]
thanks!

**Pull request merged**
