### PR TITLE
test: Moved test dependencies to import_map.json

### PR DESCRIPTION
**Pull request by cdoremus**
Moved all dependencies for unit test files to `deps.test.ts`. Upgraded dependencies to latest std version std@0.92.0.

### CODE REVIEW

**Comment by ije** [comment]
@cdoremus thanks! like i talked on discord server, please update the import map then use it in the test commad

**Comment by cdoremus** [comment]
@ije Thanks. I'll make those changes in the morning. It is after midnight here.

**Comment by ije** [comment]
@cdoremus good night! please check the changes i reverted when you're free: https://github.com/alephjs/aleph.js/tree/8b0c830985053f4eab2ff0fb972f090f20b97a6b

**Review by ije — APPROVED** [review]
looks good, thanks @cdoremus

**Pull request merged**
