### PR TITLE
fix: Decode server.ts URLs global (#88)

### PR DESCRIPTION
**Pull request by FallingSnow**

### CODE REVIEW

**Comment by FallingSnow** [comment]
Failed test is due to #92.

**Review by shadowtime2000 — COMMENTED** [review]
lgtm but I think it may be a good idea to merge once the tests pass just to make sure it works

**Review by shadowtime2000 — CHANGES_REQUESTED** [review]
if u merge master into this the tests should pass now. Also there was a restructure of the project so you will have to move ur changes

**Review by shadowtime2000 — APPROVED** [review]
lgtm

**Pull request merged**
