### PR TITLE
Simple Init UI

### PR DESCRIPTION
**Pull request by shadowtime2000**
Adds a simple init UI with [deno-cliffy/prompt/Input](https://github.com/c4spar/deno-cliffy/tree/master/prompt#%EF%B8%8F-input).

### CODE REVIEW

**Comment by ije** [comment]
cool, thanks @shadowtime2000 , more *UI* details please!

FYI:
- **Config interface**: https://github.com/alephjs/aleph.js/blob/master/types.ts#L36
- **Aleph templates repo**: https://github.com/alephjs/alephjs-templates

**Comment by shadowtime2000** [comment]
@ije I added the Aleph templates repo along with Visual Studio Code, but I think asking questions for the `aleph.config.js` may be a little unnecessary. I could instead have it write the `aleph.config.js` with all the default values so it is much easier for users to configure it.

**Comment by Hunam6** [comment]
Yes, and specify at the beginning of the file that it is not necessary and that it can be safely deleted.

**Comment by ije** [comment]
thanks @shadowtime2000, i mean we can provide some basic options, like `scrDir`, `defaultLocale`, use `sass` or not... not all the configuration

**Comment by ije** [comment]
i really dont like config files, too complex, like `webpack.config.json`, `ts.config.json`..., if we can offer a command UI to help to configure the started app it will be vary nice.

**Comment by shadowtime2000** [comment]
Pretty stale PR, will work on this later

**Pull request closed without merging**
