### PR TITLE
feat: created new multiparser

### PR DESCRIPTION
**Pull request by shinspiegel**
Hi!

After we talk on the #35, I did created a new parser for this project. I did use as a base structure the parser from [deligenius/multiparser](https://github.com/deligenius/multiparser).

Besides that I did change the try/catch block, know any error should be resolved in the request function instead of the API call, that's what you thought in the #35, right?

Any suggestions to improve this parser?

### CODE REVIEW

**Comment by ije** [comment]
well done Jeferson @shinspiegel , it looks so great, can you please add a simple testing?

**Review by ije — APPROVED** [review]

**Comment by ije** [comment]
thanks

**Comment by shinspiegel** [comment]
Sure thing!
I did created a simple test, I did never used Deno.test before, I think it's working. 
I guess it looks like Jest, which is nice to tell the truth.

**Comment by ije** [comment]
so good!

**Review by ije — APPROVED** [review]

**Pull request merged**
