### PR TITLE
Plugin env

### PR DESCRIPTION
**Pull request by alfredosalzillo**
Added an env plugin to replace `{{ENV_VAR_NAME}}` with the value at compile time.

## Why

It's useful to use env variables in **SSG** mode or **SSR** without using the `useDeno` hook.

## Example usage

```typescript
// file aleph.config.js
import env from 'https://deno.land/x/aleph/plugins/env.ts'
export default {
  plugins: [
   env(),
  ],
};
```

into code 

```typescript
const API_URL = '{{APP_BASE_API_URL}}';
```
will replace `{{APP_BASE_API_URL}}` with the result of `Deno.env.get('APP_BASE_API_URL')`.

### CODE REVIEW

**Review by shadowtime2000 — CHANGES_REQUESTED** [review]
Not a big fan of the idea of replacing `{{env variable}}`. Might better to use some AST transformations instead.

**Comment by alfredosalzillo** [comment]
The problem with an AST transformation is that as of today there isn't any AST library for deno. We should use the node `typescript.compileSource`.

Adding the AST API to the deno namespace was discussed but for now, is on standby [https://github.com/denoland/deno/pull/6893#issuecomment-672925436](https://github.com/denoland/deno/pull/6893#issuecomment-672925436).

**Comment by shadowtime2000** [comment]
@alfredosalzillo The Deno team has decided [not to have an AST API in the Deno namespace](https://github.com/denoland/deno/issues/2355#issuecomment-719522155) but there are other solutions, like [deno_swc](https://github.com/nestdotland/deno_swc) which seems like a good one.

**Comment by shadowtime2000** [comment]
I am going to close this PR, I am going to open another issue to discuss this before we implement it.

**Pull request closed without merging**
