### PR TITLE
Land 0.3 beta

### LINKED ISSUE #304: Do not process .css files in public/ folder
I tried to include [tailwind.min.css](https://esm.sh/tailwindcss/dist/tailwind.min.css), which is very big, in my public/ folder directly instead of using its url

However, `aleph build` hangs when building that file

It would be cool if we could ignore some files from the processing, either manually or when the file is named ".min.css"

### LINKED ISSUE #323: Support import_map.json in aleph.config.ts
Currently, it is not possible to use import_map.json with aleph.config.ts.

It results in an error like the following:
```
Check file:///home/noverby/Work/radikal/radikalwiki-aleph/aleph.config.ts
error: Uncaught (in promise) TypeError: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Config'.
import type { Config } from 'aleph/types'
              ~~~~~~
    at file:///home/noverby/Work/radikal/radikalwiki-aleph/aleph.config.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'config'.
import { config } from "dotenv";
         ~~~~~~
    at file:///home/noverby/Work/radikal/radikalwiki-aleph/aleph.config.ts:2:10

Found 2 errors.
        let { default: v } = await import('file://' + p)
                             ^
    at async loadConfig (https://deno.land/x/aleph@v0.3.0-alpha.33/server/config.ts:58:30)
    at async Promise.all (index 0)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:99:33)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.33/server/stdserver.ts:29:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.33/cli/dev.ts:24:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts:100:3)
```

It would be neat if we could add support for it.

### PR DESCRIPTION
**Pull request by ije**
- [x] Rewrite `Plugin` system, register moudle loader in plugin `setup` method instead of  `LoaderPlugin`
- [x] Use deno **native http** instead of std http
  - [x] Support API routes **middleware**
  - [x] Rewrite `APIRequest`
- [ ] Implement `analyze` command (show aleph app dependency graph)
  - [x] analyzer
  - [x] bundle code using accurate dependency graph
  - [ ] UI
- [x] improve **SSR**
  - [x] strip `ssr` code in browser
  - [x] support page ssr options
  ```jsx
  import type { SSROptions, Router } = 'aleph/types.ts'

  export const ssr: SSROptions = {
    props: async (router: Router) => ({ ... }),
    paths: async () => [ ... ],
  }
  
  export default function Index(ssrProps) {
    return (
      <div>ssr props: {ssrProps}</div>
    )
  }
  ```
- [x] CSS Modules Magic
  ```tsx
  import React from "https://esm.sh/react";
  
  export default function App() {
    return (
      <>
        <link rel="stylesheet"  href="../style/app.module.css" />
        <h1 className="$title $bold">Hi :)</h1>
        <p className="$intro">Welcome!</p>
      </>
    );
  }
  ```
- [x] Improve dev **bootstrap** time for large app (dynamic compile on demand)
- [x] Improve `injectCode` api
- [x] Improve HMR (refresh page when `useDeno` was updated)
- [x] Support import maps in aleph.config.ts (fix #323)
- [x] Don't resolve remote deps in API modules
- [x] Don't process `.css` files in `./public` folder (fix #304)
- [x] Update docs (https://github.com/alephjs/alephjs.org/pull/38)
- [ ] Bugfixs
  - [ ] #126
  - [ ] #300
  - [ ] #308
  - [ ] #319
  - [x] #320
  - [x] #341
  - [ ] #347

### CODE REVIEW

**Comment by hazae41** [comment]
Why would someone use "getStaticProps" when he can use "useDeno"? 

Same problem with "getStaticPaths" and "useRouter" with default values

I feel these functions are useful when not using hooks, but we are

**Comment by ije** [comment]
@hazae41 yeah, i never write a class component...not just because the class component doesn't support fast refresh, FC is more simple and hooks is great! but as a framework we have to provide some hocs like `withRouter` to resolve some edge cases, but `withDeno` for `useDeno` is kind of misunderstood, i prefer provide compatibility with nextjs's `getstaticprops` resolution

**Comment by ije** [comment]
@hazae41 @shadowtime2000 how about this:

```jsx
export async function ssr() {
  return {
    staticPaths: [],
    data: {}
  }
}

export default function App({ data }) {
  return (
    <div>ssr data: {data}</div>
  )
}
```

**Comment by FallingSnow** [comment]
I'd like to nominate #126 for the bugfixes.

**Comment by guiguan** [comment]
SPA mode in current branch:
`aleph.config.ts`
```
import type { Config } from "./../aleph.js/types.ts";

export default (): Config => ({
  ssr: false,
});
```

`ALEPH_DEV_PORT=8081 aleph dev -p 3030` will result in the following error:
```
Error: framework renderer is undefined
Error: framework renderer is undefined
    at Object.render (file:///[redacted]/aleph.js/server/ssr.ts:44:52)
    at Renderer.renderSPAIndexPage (file:///[redacted]/aleph.js/server/ssr.ts:175:60)
    at async file:///[redacted]/aleph.js/server/app.ts:605:17
    at async Renderer.cache (file:///[redacted]/aleph.js/server/ssr.ts:77:24)
    at async Application.getPageHTML (file:///[redacted]/aleph.js/server/app.ts:604:22)
    at async Server.handle (file:///[redacted]/aleph.js/server/server.ts:224:30)
```

hacking this line https://github.com/alephjs/aleph.js/blob/feat-0.3-beta/server/app.ts#L215 to `if (true) {` seems to fix the problem. Any better idea?

**Comment by guiguan** [comment]
probably this is better https://github.com/alephjs/aleph.js/pull/342

**Comment by ije** [comment]
@guiguan thanks, i didn't run the `spa` example for those changes. in spa mode the server should not render pages, so the renderer is undefined ad expected, I must missed something will look into it.

**Comment by vincenzopalazzo** [comment]
Do you think that this PR it is big enough to make a breakpoint and put it on the master?

I would like to make a review of it, but it really big, it can take one day of my time.

**Comment by ije** [comment]
@vincenzopalazzo thanks, but i think it is hard to review since i changed a lot of things...any how, i already finished the doc updating, will merge this branch to master after final check on docs.

**Pull request merged**
